### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received [ '~/Project/react/projectname/name-name/sr...

### ISSUE THREAD

**Issue by kunall17** [m-hall/eslint-fixer#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [eslint-fixer](https://github.com/m-hall/eslint-fixer) package 1.2.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received [ '/Users/name/Project/react/projectname/name-name/src/name.js' ]

```
At path.js:7

TypeError: Path must be a string. Received [ '/Users/name/Project/react/name/name-name/src/name.js' ]
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1229:5)
    at /packages/eslint-fixer/lib/atom-eslint-fix.js:40:28
    at Array.forEach (native)
    at Object.getCurrentWorkingDir (/packages/eslint-fixer/lib/atom-eslint-fix.js:38:37)
    at Object.exec (/packages/eslint-fixer/lib/atom-eslint-fix.js:82:24)
    at Object.runTreeView (/packages/eslint-fixer/lib/atom-eslint-fix.js:65:14)
    at /packages/eslint-fixer/lib/atom-eslint-fix.js:28:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:45.9.0 core:backspace (input.hidden-input)
     -0:44.2.0 core:select-all (input.hidden-input)
  6x -0:42 core:backspace (input.hidden-input)
     -0:40.1.0 core:confirm (input.hidden-input)
     -0:29 atom-beautify:beautify-file (span.name.icon.icon-file-text)
     -0:23.5.0 tree-view-copy-relative-path:copy-path (span.name.icon.icon-file-text)
  3x -0:22.6.0 core:move-right (input.hidden-input)
  6x -0:22.1.0 core:select-left (input.hidden-input)
     -0:20.7.0 core:paste (input.hidden-input)
  3x -0:20.1.0 core:backspace (input.hidden-input)
     -0:19.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:18.8.0 core:save (input.hidden-input)
     -0:17.4.0 editor:newline (input.hidden-input)
     -0:12.3.0 core:undo (input.hidden-input)
     -0:09.4.0 atom-eslint-fix:run-tree-view (span.name.icon.icon-file-text)
     -0:06.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-terminal 0.8.0 
case-keep-replace 0.5.0 
color-picker 2.2.5 
eslint-fixer 1.2.1 
git-diff-details 1.4.0 
linter 1.11.23 
linter-eslint 8.1.3 
local-history 4.0.1 
multi-cursor 2.1.5 
navigate 0.1.17 
nuclide 0.209.0 
nuclide-format-js 0.0.36 
tree-view-copy-relative-path 1.1.0 
```

**Comment by m-hall** [comment]
Fixed in 1.3.0.
Sorry for the delay
