### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by adius** [m-hall/eslint-fixer#2]
[Enter steps to reproduce below:]
1. Open file
2. Execute "Atom Eslint Run: Fix"

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [eslint-fixer](https://github.com/m-hall/eslint-fixer) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/adrian/dotfiles/home/atom/packages/eslint-fixer/lib/atom-eslint-fix.js:59

TypeError: Cannot read property 'replace' of undefined
    at Object.AtomEslintFix.exec (/Users/adrian/dotfiles/home/atom/packages/eslint-fixer/lib/atom-eslint-fix.js:59:65)
    at Object.AtomEslintFix.run (/Users/adrian/dotfiles/home/atom/packages/eslint-fixer/lib/atom-eslint-fix.js:33:14)
    at atom-workspace.atom.commands.add.atom-eslint-fix:run (/Users/adrian/dotfiles/home/atom/packages/eslint-fixer/lib/atom-eslint-fix.js:21:51)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:11.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 10x -0:04.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 atom-eslint-fix:run (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-smalltalk",
      "terminal",
      "atom-lint",
      "linter-chktex",
      "travis-ci-status",
      "term2",
      "deprecation-cop",
      "about",
      "background-tips",
      "metrics",
      "package-generator",
      "release-notes",
      "styleguide",
      "update-package-dependencies",
      "welcome",
      "npm-docs",
      "coffee-compiler",
      "vim-mode",
      "terminal-plus",
      "Hydrogen",
      "js-refactor",
      "markdown-preview",
      "language-markdown",
      "linter-jshint",
      "linter-jscs",
      "language-vue-component",
      "linter-js-standard",
      "standard-formatter",
      "standardjs-snippets",
      "browser-plus",
      "preview-plus",
      "tablr",
      "indent-guide-improved",
      "linter-eslint"
    ],
    "followSymlinks": true,
    "projectHome": "~/Projects",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
AtLilyPond, v1.2.0
Stylus, v3.0.0
Sublime-Style-Column-Selection, v1.5.1
auto-detect-indentation, v1.1.0
autocomplete-clang, v0.9.3
autocomplete-emojis, v2.5.0
autocomplete-paths, v1.0.2
distraction-free-mode, v0.11.5
eslint-fixer, v1.0.0
fast-eslint, v2.13.0
file-icons, v1.7.15
file-types, v0.5.1
fold-functions, v0.4.3
git-diff-details, v1.3.0
hex, v0.6.2
keyboard-scroll, v0.4.0
language-arduino, v0.4.1
language-diff, v0.4.0
language-docker, v1.1.6
language-gitignore, v0.2.0
language-ipynb, v1.3.0
language-jade, v0.7.1
language-json5, v1.1.0
language-latex, v0.6.1
language-nginx, v0.6.1
language-openscad, v0.4.3
language-pug, v0.0.17
language-svg, v0.9.0
language-vcard, v0.2.0
language-vue, v0.14.0
linter, v1.11.11
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
make-executable, v0.1.1
markdown-preview-plus, v2.4.0
markdown-table-formatter, v2.8.3
merge-conflicts, v1.4.4
pdf-view, v0.50.0
refactor, v0.6.0
svg-preview, v0.7.4
tabs-to-spaces, v1.0.2
tabular, v0.1.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by m-hall** [comment]
Your command list shows that you changed the file (core:backspace). Unfortunately at this point it is not capable of lint files that are changed.
I was planning to add that, but since eslint doesn't support --fix'ing a buffer like that, it will require copying the contents to a temp file, linting it, then copying it back over the buffer.

**Comment by tkssharma** [comment]
getting same any fix for this ??

**Comment by m-hall** [comment]
I think I've fixed this now; it appears that when I changed the name of the package I forgot to change the prefix used for getting settings. It worked for me because I still had the old settings in my config.

Can one of you update the package and close this issue if it works?
